# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api/requirements"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
