version: "3.7"

services:

  django:
    container_name: memewars-django
    build:
      context: ./api
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: memewars-postgres
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - memewars-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  nextjs:
    container_name: memewars-nextjs
    build:
      context: ./app
      target: production
    env_file:
      - .env
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  memewars-postgres-data:
