version: "3.7"

services:

  django:
    container_name: memewars-django
    build:
      context: ./api
    env_file:
      - .env
    ports:
      - "8000:8001"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: memewars-postgres
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - memewars-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  react:
    container_name: memewars-react
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - "3000:3001"
    restart: unless-stopped

volumes:
  memewars-postgres-data:
