version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run:
          name: Testing
          command: pwd; ls -la; python --version; docker --version

workflows:
  test-workflow:
    jobs:
      - test
