version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - run:
          name: Testing
          command: pwd; ls -la; python --version; docker --version

workflows:
  test-workflow:
    jobs:
      - test
