version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Prepare Environment variables
          command: cp example.env .env
      - run:
          name: Prepare Environment variables
          command: cp example.env .env
      - run:
          name: Building Docker Images
          command: docker compose -f docker-compose.circleci.yml build --no-cache
      - run:
          name: Run Tests
          command: | 
            docker compose -f docker-compose.circleci.yml run --rm django sh /app/scripts/entrypoint.sh test
      - run:
          name: "Checking Docker data | before cleanup (TODO: REMOVE)"
          command: docker image ls; docker volume ls; docker network ls; docker container ls
      - run:
          name: Cleanup Docker Data
          command: docker system prune -a -f
      - run:
          name: "Checking Docker data | after cleanup (TODO: REMOVE)"
          command: docker image ls; docker volume ls; docker network ls; docker container ls

workflows:
  test-workflow:
    jobs:
      - test
