version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - run:
          name: Prepare Environment variables
          command: cp example.env .env
      - run:
          name: Run Tests
          command: docker compose run --rm django sh /app/scripts/entrypoint.sh test

workflows:
  test-workflow:
    jobs:
      - test
