version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python
    steps:
      - checkout
      - run:
          name: Testing
          command: pwd

workflows:
  test-workflow:
    jobs:
      - test
