version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Prepare Environment variables
          command: cp example.env .env
      - run:
          name: Prepare Environment variables
          command: cp example.env .env
      - run:
          name: Checking Git Status
          command: git status
      - run:
          name: Run Tests
          command: | 
            docker compose -f docker-compose.circleci.yml run --rm django sh /app/scripts/entrypoint.sh test

workflows:
  test-workflow:
    jobs:
      - test
